### ISSUE TITLE
Five EMPTY git repositories in openela-main - Commonility: 4 of the 5 have a '+' in the original package name

### ISSUE THREAD

**Issue by illumino** [openela/issues#152]
Five (5) of the 3084 repositories in https://github.com/openela-main/ are EMPTY git repositories containing no files. With the exception of "dbus-c-" which I can not determine the matching package of; the rest  seem to have a common naming convention, of using '+' in the original package  name.

==========================================================================

```
Discovered Empty Repositories                           Matching Package

https//github.com/openela-main/dbus-c-                  ???
https//github.com/openela-main/dvd-rw-tools             dvd+rw-tools
https//github.com/openela-main/libsigc-20               libsigc++20
https//github.com/openela-main/memtest86-               memtest86+
https//github.com/openela-main/perl-Text-Tabs-Wrap      perl-Text-Tabs+Wrap
```
==========================================================================

Rocky Linux 8.10 Packages Match Empty Repository Names

```
# [root@rocky8] % cat /etc/redhat-release 
Rocky Linux release 8.10 (Green Obsidian)

# [root@rocky8] % dnf search dbus\*c\*      
dbus-common.noarch : D-BUS message bus configuration
group-service.x86_64 : Dbus Group management CLI tool

# [root@rocky8] % dnf search dvd\*rw\*tools 
dvd+rw-tools.x86_64 : Toolchain to master DVD+RW/+R media

# [root@rocky8] % dnf search libsigc
libsigc++20.i686 : Typesafe signal framework for C++
libsigc++20.x86_64 : Typesafe signal framework for C++

# [root@rocky8] % dnf search memtest86
memtest86+.x86_64 : Stand-alone memory tester for x86 and x86-64 computers

# [root@rocky8] % dnf search perl-Text-Tabs
perl-Text-Tabs+Wrap.noarch : Expand tabs and do simple line wrapping

```
==========================================================================

Rocky Linux 9.4 Packages Match Empty Repository Names

```
# [root@rocky9] # cat /etc/redhat-release 
Rocky Linux release 9.4 (Blue Onyx)

# [root@rocky9] # dnf search dbus\*c\*      
dbus-common.noarch : D-BUS message bus configuration
group-service.x86_64 : Dbus Group management CLI tool

# [root@rocky9] # dnf search dvd\*rw\*tools 
dvd+rw-tools.x86_64 : Toolchain to master DVD+RW/+R media

# [root@rocky9] # dnf search libsigc
libsigc++20.x86_64 : Typesafe signal framework for C++
libsigc++20.i686 : Typesafe signal framework for C++

# [root@rocky9] # dnf search memtest86
memtest86+.x86_64 : Stand-alone memory tester for x86 and x86-64 computers

# [root@rocky9] # dnf search perl-Text-Tabs
perl-Text-Tabs+Wrap.noarch : Expand tabs and do simple line wrapping

```
==========================================================================

**Comment by aburmash** [comment]
Just in case:
for OpenELA repository names there is substitution on place for + to plus, so
https://github.com/openela-main/dbus-cplusplus
https://github.com/openela-main/dvdplusrw-tools
https://github.com/openela-main/libsigcplusplus20
https://github.com/openela-main/memtest86plus
https://github.com/openela-main/perl-Text-TabsplusWrap

As for empty repos - we'll check if they can be safely removed and will do it.

**Comment by aburmash** [comment]
resolved, should not be seen.
